[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
pretty_env_logger = "0.5.0"
handlebars = { version = "5.1.2", features = ["dir_source"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
